import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Starwars App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 `}>
        <header className="text-xl font-bold leading-[3rem]">Starwars App</header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[3rem] opacity-70">
          © {new Date().getFullYear()} Starwars App By David Cordoba
        </footer>
      </body>
    </html>
  );
}
